### ISSUE TITLE
[최인호] Eureka 서비스 배포 가이드 (Maven + GitHub Actions + 서버 실행)

### ISSUE THREAD

**Issue by dusen0528** [nhnacademy-aiot2-pangyo-coffee-legends/study#21]
# Step 1 IntelliJ ./github/workflows/maven.yml
## Github Actions 구성 설명
```
name: Eureka CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: upload eureka jar to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "target/*.jar"
          target: "~/eureka/"
          rm: false

      - name: execute eureka startup script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: "cd ~/eureka && ./startup.sh"
```

1. **`on.push` / `on.pull_request`**  
   → `main` 브랜치에 push되거나 PR이 생성되면 자동으로 워크플로우 실행됨.

2. **`runs-on: ubuntu-latest`**  
   → GitHub에서 제공하는 최신 Ubuntu 환경에서 실행됨.

3. **`actions/checkout@v3`**  
   → 현재 저장소 코드를 가져옴.

4. **`actions/setup-java@v3`**  
   → JDK 21 설치. 우리가 Java 21로 서버 돌리니까 반드시 필요함.

5. **`Build with Maven`**  
   → Maven으로 프로젝트를 빌드해서 `.jar` 파일 생성.  
   `mvn -B package --file pom.xml` 명령어는 `pom.xml` 기준으로 패키징함.  
   이때 `pom.xml`의 `<finalName>` 설정에 따라 `target/eureka-service.jar` 로 생성됨.

6. **`upload eureka jar to server`**  
   → `appleboy/scp-action` 사용해서 jar 파일을 서버 `~/eureka/` 디렉토리에 업로드함.

7. **`execute eureka startup script`**  
   → `appleboy/ssh-action` 사용해서 서버에 접속하고 `startup.sh` 실행해서 서비스 재시작함.

> 💡 GitHub 저장소에는 Secrets에 SSH 설정값이 들어가 있어야 함

![Image](https://github.com/user-attachments/assets/a7c085b1-80fa-42e7-b984-423d788cbcce)

# Step 2 서버 실행 스크립트 만들기
- 경로 : ~/eureka/startup.sh
```
aiot2-team2@ubuntu:~/eureka$ nano startup.sh
aiot2-team2@ubuntu:~/eureka$ cat startup.sh
kill -15 $(lsof -ti :10252)

/usr/local/java/java21/bin/java -Dserver.port=10252 -jar ~/eureka/eureka-service.jar > eureka.log 2>&1 &
```
nano 통해서 위와 같이 작성
- 기존 실행중인 10252 포트 종료 후 
- jar파일 실행시킴

### 💡 꼭 실행 권한 주기 !!
```
chmod +x startup.sh 
```

# 🚀 배포 흐름 요약

1. 로컬에서 main 브랜치에 push → GitHub Actions 실행됨

2. Maven 빌드 후 eureka-service.jar 생성됨

3. 서버 ~/eureka/에 jar 복사됨

4. 서버에서 startup.sh 로 기존 프로세스 종료 + 새 jar 실행됨

- startup.sh 는 서비스별로 하나씩 관리하면 편함 !!
